//“—≤π≥‰÷¡2012
#define KEYWORDS_1364_1995 \
    { "always", TokenKind::AlwaysKeyword },\
    { "and", TokenKind::AndKeyword },\
    { "assign", TokenKind::AssignKeyword },\
    { "begin", TokenKind::BeginKeyword },\
    { "buf", TokenKind::BufKeyword },\
    { "case", TokenKind::CaseKeyword },\
    { "default", TokenKind::DefaultKeyword },\
    { "else", TokenKind::ElseKeyword },\
    { "end", TokenKind::EndKeyword },\
    { "for", TokenKind::ForKeyword },\
    { "function", TokenKind::FunctionKeyword },\
    { "if", TokenKind::IfKeyword },\
    { "nor", TokenKind::NorKeyword },\
    { "not", TokenKind::NotKeyword },\
    { "or", TokenKind::OrKeyword },\
    { "while", TokenKind::WhileKeyword },\
    { "unsigned", TokenKind::UnsignedKeyword },\
    { "include", TokenKind::IncludeKeyword },\
    { "byte", TokenKind::ByteKeyword },\
    { "class", TokenKind::ClassKeyword },\
    { "const", TokenKind::ConstKeyword },\
    { "continue", TokenKind::ContinueKeyword },\
    { "enum", TokenKind::EnumKeyword },\
    { "expect", TokenKind::ExpectKeyword },\
    { "extern", TokenKind::ExternKeyword },\
    { "final", TokenKind::FinalKeyword },\
    { "foreach", TokenKind::ForeachKeyword },\
    { "import", TokenKind::ImportKeyword },\
    { "int", TokenKind::IntKeyword },\
    { "new", TokenKind::NewKeyword },\
    { "null", TokenKind::NullKeyword },\
    { "protect", TokenKind::ProtectKeyword },\
    { "rand", TokenKind::RandKeyword },\
    { "random", TokenKind::RandomKeyword },\
    { "return", TokenKind::ReturnKeyword },\
    { "static", TokenKind::StaticKeyword },\
    { "string", TokenKind::StringKeyword },\
    { "struct", TokenKind::StructKeyword },\
    { "this", TokenKind::ThisKeyword },\
    { "type", TokenKind::TypeKeyword },\
    { "typedef", TokenKind::TypedefKeyword },\
    { "union", TokenKind::UnionKeyword },\
    { "unique", TokenKind::UniqueKeyword },\
    { "virtual", TokenKind::VirtualKeyword },\
    { "void", TokenKind::VoidKeyword },\
    { "soft", TokenKind::SoftKeyword }
